### ISSUE TITLE
Cannot install v1.2.3 from PyPI on Python 3.12

### ISSUE THREAD

**Issue by titodalcanton** [pypmc/pypmc#104]
The 1.2.3 release available on PyPI cannot be installed on Python 3.12, because it includes no wheels for Python 3.12 and no source distribution:

https://pypi.org/project/pypmc/1.2.3/#files

**Comment by dvandyk** [comment]
@titodalcanton Thank you very bringing this to our attention. We now provide the source distribution and the Python 3.12 wheels as of version 1.2.4.
