### ISSUE TITLE
Issues installing pypmc on Windows 10

### ISSUE THREAD

**Issue by tiseever** [pypmc/pypmc#61]
Whenever I run the setup.py through pip or directly through python it gives me this error:
![Coding Error Image](https://i.gyazo.com/1ee7b7b3f93ee5ed4d8648d8bbac0f2e.png)
I went into the setup.py and fiddled with the code and found that these lines were causing the errors:
![Setup.py Code Issue](https://i.gyazo.com/d28e06aa50a918b200a9b375ef3ba2bb.png)
It allows me to install pypmc if I delete the commands inside the extra_compile_args function, but then it doesn't function properly as it can not import the name 'gauss'.

**Comment by fredRos** [comment]
Ok, I guess you may be the first one to try this out on windows. I apologize for not being clear in the documentation, we only tested `pypmc` on linux and mac. No wonder it fails when I pass GCC-style arguments to the Microsoft C compiler. Before I delve into this, can you post what the error was when you import the module?

**Comment by fredRos** [comment]
Note: in `setup.py`, I state that 

    platforms=['Unix'],

so we never tried to get it to run on windows. But if doesn't take much effort to get it to work there, why not? I don't have a windows machine so I'd need some more feedback from @tiseever to fix that

**Comment by tiseever** [comment]
The error that was passed when I imported the module was this:
![Code error](https://i.gyazo.com/1ffc9710876a718ab3922ac0ceba0acc.png)

I managed to get Ubuntu - a GCC compiler - working a bit earlier today with python and I got that to run with python to try to install it, and it passed this error:
![GCC-Code error](https://i.gyazo.com/beff0f2936df3590aa755a9ce33c67ed.png)

I'm thinking it may have to do with the compiler so I'm setting up the MinGW compiler now to see if it makes any difference since that comes with C/C++ tools along with the compiler, unlike Ubuntu.

**Comment by tiseever** [comment]
Alright I got the MinGW compiler working, the DLL issues were caused by Ubuntu; however, there are still some issues with the isntallation using the MinGW compiler:
![MinGW compiler](https://i.gyazo.com/666e5170e92b439ea106af1565c64960.png)

**Comment by dvandyk** [comment]
@tiseever Sorry for the late handling. Unless somebody comes forward to fix Windows issues and commits to server as the pypmc maintainer for Windows, we will not support pypmc under Windows.

Closes as ``wontfix``.
