### ISSUE TITLE
Run tests and deploy wheels to PyPI using Github Actions

### ISSUE THREAD

**Issue by dvandyk** [pypmc/pypmc#74]
# Acceptance criteria

- [ ] tests are run on github actions for python 3.6, 3.7, 3.8
- [ ] wheels are build for every commit
- [ ] building from tar ball is testes for every commit, preferably on the latest version of ubuntu
- [ ] wheels are deployed for tagged commits
- [ ] documentation is deployed for every commit to master

**Comment by fredRos** [comment]
@dvandyk Roger that! **Allow all actions**

**Comment by fredRos** [comment]
@dvandyk Welcome at the other side. I made you a maintainer of this repository and you can now create secrets etc. to get actions up and running. I thought about it and think if you are more comfortable with github actions these days, then let's take that route. I'm editing the issue description to make the task more concrete

**Comment by fredRos** [comment]
Something to keep in mind when testing for packaging https://github.com/mtazzari/galario/issues/183#issuecomment-790912649
