### ISSUE TITLE
Update repository in the pypmc organization

### ISSUE THREAD

**Issue by fredRos** [pypmc/pypmc#77]
As I don't have much time to spare, I will migrate this repo from my personal account to the new pypmc organization to facilitate help from the community of users. Thanks @dvandyk for offering help with maintenance of pypmc

- [ ] @fredRos  to create fork and put up a redirect on gh pages to docs because [If the transferred repository contains a GitHub Pages site, then links to the Git repository on the Web and through Git activity are redirected. However, we don't redirect GitHub Pages associated with the repository.](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository)
- [ ] update secrets
- [ ] use actions instead of travis ci? Not sure this is needed, as I just had to log back in to travis to enable proper permissions for travis to see github updates
- [ ] make the next release the first one from the new repo

**Comment by dvandyk** [comment]
@JohannesBuchner might be interested in this

**Comment by fredRos** [comment]
Closing this to create separate issues. This was more of a milestone issue but I created https://github.com/pypmc/pypmc/milestone/5 for that
