### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by fredRos** [pypmc/pypmc#78]
- [x] update links in docs to new URL pypmc.github.io/pypmc
- [x] update theme: old matplotlib theme looks dated now
- [x] update copyright notice: definitely year, authors?
- [ ] ~~have a fresh look: text out of date?~~
- [ ] ~~add section with testimonials or others using pypmc, either in docs or in readme~~

**Comment by dvandyk** [comment]
@fredRos ```pypmc.github.io``` does not exist yet. Also, you don't need the trailing ```/pypmc``` anymore.

**Comment by dvandyk** [comment]
- ``docs/`` fixed as of f87b357

**Comment by dvandyk** [comment]
Current documentation has problems with ``automodule`` for ``density``, ``mix_adapt`` and ``tools``. But ``sampler`` works!?

**Comment by dvandyk** [comment]
Updated theme to ``sphinx_rtd_theme``, same as from ReadTheDocs.io

Fixed problem with the documentation. In that process, merged API doc / reference guide into one file (otherwise, numbering for reference guide starts again with 1., and is listed in the TOC in the left side bar).

**Comment by dvandyk** [comment]
- I don't have the time right now to completely read the docs for updates, removing that from list.
 - testimonials are not a blocker for v1.2, removing those as well

**Comment by dvandyk** [comment]
Resolved through 2b3c03c, 25a044d, f61f70f, and 7b80d98.
