### ISSUE TITLE
Fix old link to docs

### ISSUE THREAD

**Issue by fredRos** [pypmc/pypmc#79]
# Issue

After migrating the repo from `fredRos/pypmc`, the existing link to docs doesn't work anymore:

http://fredros.github.io/pypmc/html/ yields a 404

# Steps

- [ ] @fredRos  to create fork and put up a redirect on gh pages to docs because [If the transferred repository contains a GitHub Pages site, then links to the Git repository on the Web and through Git activity are redirected. However, we don't redirect GitHub Pages associated with the repository.](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository)

# Acceptance criteria

- [ ] Link to http://fredros.github.io/pypmc/html/ redirects to http://pypmc.github.io/pypmc/html/

**Comment by dvandyk** [comment]
I have
 - created a separate repository for the entire pypmc org (pypmc/pypmc.github.io), and initialised it manually
 - GitHub Actions workflow update that repository on each commit
 - new links are https://pypmc.github.io/, no path needed
 - adjusted links in the README.md

**Comment by dvandyk** [comment]
I think this can be closed now.
