### ISSUE TITLE
Drop support for python2

### ISSUE THREAD

**Issue by fredRos** [pypmc/pypmc#80]
# Why

Python2 has reached end of life and from 1.2 and onwards, we won't test the code on that platform anymore. Occasionally, the code is more complex to support two major version of python

# Acceptance criteria

- [x] All source code can be freed of compatibility constructs to make it work with python 2 and 3
- [x] the Makefile is cleaned up
- [x] the docs updated

**Comment by dvandyk** [comment]
Makefile cleaned up in 111eeac

**Comment by dvandyk** [comment]
Docs cleaned up in c4140fc

**Comment by dvandyk** [comment]
We presently import the following from ``__future__``:
 - [ ]``division``
 - [ ]``print_function``
I will remove both.

**Comment by dvandyk** [comment]
- ``print_function`` removed in b223be03a177606cc1cb6d5bfa4e64ba38581c32 and 4eef16d9ac172c0b5cb72d172ae7ee242ea3baf9
 - ``division`` removed in 071ee5379361b41c5a32b95a7c41d333f6c5aea6
