### ISSUE TITLE
Add TWINE_USERNAME and TWINE_PASSWORD to repository secrets

### ISSUE THREAD

**Issue by dvandyk** [pypmc/pypmc#81]
Needed before we can release v1.2

**Comment by dvandyk** [comment]
@fredRos ping!

**Comment by fredRos** [comment]
@dvandyk I guess there is no TWINE password or username but what's needed are the PYPI user name and password? I added those as repository secrets. Let me know if we can then close this issue

**Comment by dvandyk** [comment]
Thanks @fredRos! The name is not terribly relevant. The repo secret is exposed to ``twine`` using two environment variables. I adjusted the workflow by changing the name of the secret when export the variables:

https://github.com/pypmc/pypmc/blob/4145a6ab234dee89f7dec570b83d2b09da6471a5/.github/workflows/manylinx-build%2Bcheck%2Bdeploy.yaml#L94-L95
