### ISSUE TITLE
Error in the Cholesky decomposition stops the program

### ISSUE THREAD

**Issue by mreboud** [pypmc/pypmc#91]
When updating a component I encounter a linalg error due to a failing Cholesky decomposition `numpy.linalg.LinAlgError: 10-th leading minor of the array is not positive definite`. The error is caused by these lines https://github.com/pypmc/pypmc/blob/5f705e9c67add23e46999f8b3c2483e1593f3683/pypmc/density/gauss.pyx#L40-L43.
From the above comment I would expect this error to be silently captured and the update to continue. Or I am misunderstanding the comment?

**Comment by dvandyk** [comment]
As discussed with Meril offline, this seems fine on second look. On the EOS side, we should capture this error as it is raised.

**Comment by mreboud** [comment]
I confirm, sorry for the noise!
