### ISSUE TITLE
Clarification needed in the example concerning the 'last generated samples/weights'

### ISSUE THREAD

**Issue by mreboud** [pypmc/pypmc#94]
As @dvandyk realized in the EOS code, there is a global misunderstanding of whether PMC updates should be performed on the last step samples/weights or on all the samples/weights. The misunderstanding is also present in the documentation: https://github.com/pypmc/pypmc/blob/5f705e9c67add23e46999f8b3c2483e1593f3683/examples/pmc.py#L67-L69

By changing `[:]` by `[-1]` as it should be from the comment, the efficiency of the adaptation is greatly improved! A perplexity of 0.99 is obtained after 5 steps vs. 0.53 after 10 steps in the present version of the example!

**Comment by mreboud** [comment]
Although running on the full sample set probably yields more stable results, this would require, to my understanding, the reevaluation of each sample's weight. Since the generation of new samples is not the most time consuming part of the evaluation, I don't really see the interest of this method vs. using more samples per step

**Comment by fredRos** [comment]
@mreboud It's been a while but I think you are right. In the straight PMC update, you should only use the samples from that particular proposal to update the proposal. This may be a copy-paste error from the `combine_weights` method where indeed samples from all proposals can be reweighted and combined. 

Or we changed the behavior of the sampler later as it now appends the samples in https://github.com/pypmc/pypmc/blob/5f705e9c67add23e46999f8b3c2483e1593f3683/pypmc/sampler/importance_sampling.py#L224

Thanks for spotting this!

**Comment by fredRos** [comment]
>  Since the generation of new samples is not the most time consuming part of the evaluation, I don't really see the interest of this method vs. using more samples per step

Not sure exactly what you mean but if you use `combine_weights` as in https://github.com/pypmc/pypmc/blob/5f705e9c67add23e46999f8b3c2483e1593f3683/examples/uniting_markov_chains_and_variational_bayes.py#L175, then you can reduce the impact of outliers, which is important in high dimensions. And for that you need multiple proposals.

**Comment by mreboud** [comment]
What is the aim of `combine_weights` exactly? It is not clear to me :)

**Comment by fredRos** [comment]
@mreboud From the docs https://pypmc.github.io/introduction.html

> The power to combine the proposals of subsequent steps [Cor+12]. This increases the effective sample size per wallclock time and helps in reducing undesired samples with very large weight — outliers — that adversely affect the variance of the integral estimate.

This is the paper with all the details https://pypmc.github.io/references.html#cor-12 

It has helped me improve the effective samples size in case a single outlier drives it down to like 0.01 % in 40 dimensions. With the deterministic mixture, I would get up to say 5 % ESS on the evidence and marginal distributions that look sane
