### ISSUE TITLE
conda package

### ISSUE THREAD

**Issue by JohannesBuchner** [pypmc/pypmc#99]
Hi all,

This is just to let you know that there is now a pypmc package on conda-forge.

https://github.com/conda-forge/pypmc-feedstock
https://anaconda.org/conda-forge/pypmc

I used this to build the snowline Bayesian inference package on top of it. https://johannesbuchner.github.io/snowline/

Cheers,
             Johannes

**Comment by fredRos** [comment]
Thanks a lot @JohannesBuchner 

How hard was it to create the package?

**Comment by JohannesBuchner** [comment]
It's easy once you have made a few conda packages. The [meta.yaml](https://github.com/conda-forge/pypmc-feedstock/tree/main/recipe) is all you need. Here are the instructions: https://conda-forge.org/docs/maintainer/adding_pkgs.html#step-by-step-instructions

**Comment by dvandyk** [comment]
FYI: I've added a conda-forge badge to the README page.
